### ISSUE TITLE
启动ppd集群失败

### ISSUE THREAD

**Issue by Ikaros-suki** [secretflow/spu#100]
在终端运行
`python -m spu.utils.distributed up`

出现以下错误
```sh
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/miniconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/yp_workplace/ht_workplace/spu_try/spu/spu/__init__.py", line 18, in <module>
    from .spu_pb2 import (  # type: ignore
ModuleNotFoundError: No module named 'spu.spu_pb2'
```

相应位置具体代码为
```py
from .spu_pb2 import (  # type: ignore
    DataType,
    Visibility,
    PtType,
    ProtocolKind,
    FieldType,
    ValueProto,
    ShapeProto,
    RuntimeConfig,
    ExecutableProto,
)
```
以上结果为使用`pip install spu` 安装时出现

但在尝试使用`sh build_and_packaging.sh -i` 安装时
出现以下错误
```sh
build_and_packaging.sh: 20: Syntax error: "(" unexpected
```

具体代码为
```py
function build_spu() {
    echo -e "${RED}Start build wheel package...${NC}"

    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        docker run --rm --mount type=bind,source="$(pwd)",target=/home/admin/dev/ \
            -w /home/admin/dev \
            --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
            --cap-add=NET_ADMIN \
            --privileged=true \
            --entrypoint "./build_wheel_entrypoint.sh" \
            registry.hub.docker.com/secretflow/release-ci:latest
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        sh ./build_wheel_entrypoint.sh
    fi

    (($? != 0)) && {
        echo -e "${RED}Build exited with non-zero.${NC}"
        exit 1
    }
}
...
```

**Comment by anakinxc** [comment]
hi @Ikaros-suki 

请问您是不是从在 spu 目录下运行了
`python -m spu.utils.distributed up `

**Comment by Ikaros-suki** [comment]
hi @anakinxc 

是的, 若是在其他位置运行的话
报错应该如下
```sh
# python -m spu.utils.distributed up
/root/miniconda3/bin/python: Error while finding module specification for 'spu.utils.distributed' (ModuleNotFoundError: No module named 'spu.utils')
```

**Comment by anakinxc** [comment]
请问一下安装的 spu 的版本是多少呀

**Comment by Ikaros-suki** [comment]
spu                    0.3.1b9

**Comment by anakinxc** [comment]
Hi @Ikaros-suki 

0.3.1b9 的话，请用 `python -m spu.binding.util.distributed up` 来启动 ppd

**Comment by anakinxc** [comment]
Hi @Ikaros-suki 

请问 ppd 成功启动了吗

**Comment by Ikaros-suki** [comment]
成功了, 谢谢
