### ISSUE TITLE
PIR隐匿查询报错

### ISSUE THREAD

**Issue by meisir5648** [secretflow/spu#200]
### Issue Type

Others

### Modules Involved

PIR

### Have you reproduced the bug with SPU HEAD?

Yes

### Installation Kind

source

### SPU Version

0.3.2b12

### OS Platform and Distribution

centos8.5

### Python Version

3.8.16

### Compiler Version

gcc 11.2.1

### Current Behavior?

A bug happened!

### Standalone code to reproduce the issue

```Python
print("A bug")
```

### Relevant log output

```Shell
(spu) [root@netmpc-core1 spu]# python examples/python/pir/pir_client.py --rank 1 -in_path examples/data/test_data_query.txt -key_columns id -out_path pir_out.csv
id_0 = 127.0.0.1:10086
id_1 = 127.0.0.1:10087
2023-05-16 22:24:20.458 [info] [receiver.cc:RequestQuery:203] cuckoo table_size:341
2023-05-16 22:24:20.458 [info] [receiver.cc:RequestQuery:228] Finished inserting items with 1 hash functions; cuckoo table fill-rate: 0.002932551319648094
2023-05-16 22:24:20.460 [info] [receiver.cc:RequestQuery:280] plain_powers size:1, using_keyswitching:false
2023-05-16 22:24:20.470 [info] [receiver.cc:RequestQuery:305] encrypted_powers size: 20
Traceback (most recent call last):
  File "examples/python/pir/pir_client.py", line 96, in <module>
    app.run(main)
  File "/root/miniconda3/envs/spu/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda3/envs/spu/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "examples/python/pir/pir_client.py", line 90, in main
    report = pir.pir_client(link_ctx, config)
  File "/root/miniconda3/envs/spu/lib/python3.8/site-packages/spu/pir.py", line 48, in pir_client
    report_str = libspu.libs.pir_client(link, config.SerializeToString())
RuntimeError: what: 
        [Enforce fail at libspu/psi/utils/utils.cc:179] (proto.ParseFromArray(data.data(), data.size())). 
stacktrace: 
#0 spu::psi::LabelPsiReceiver::ProcessQueryResult()+0x7fbaa4e33844
#1 std::_Function_handler<>::_M_invoke()+0x7fbaa4e33e73
#2 std::_Function_handler<>::_M_invoke()+0x7fbaa4aeed3b
#3 yacl::internal::_parallel_run()+0x7fbaa50df211
#4 yacl::parallel_for()+0x7fbaa4af9807
#5 spu::psi::LabelPsiReceiver::RequestQuery()+0x7fbaa4e37dfb
#6 spu::pir::LabeledPirClient()+0x7fbaa4e219ee
#7 spu::pir::PirClient()+0x7fbaa4e22da4
#8 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x7fbaa3e9616f
#9 pybind11::cpp_function::dispatcher()+0x7fbaa3e707d6
#10 PyCFunction_Call+0x4f5652
```

**Comment by Chrisdehe** [comment]
hi，@meisir5648
请注意
--partyips ip0:port0,ip1:port1 --rank 0/1
指定本方是rank 0 时，必须有ip0, 端口port0没有被占用
指定本方是rank 1 时，必须有ip1, 端口port1没有被占用
检查下你的执行代码。
请严格参考[星河杯“黑名单共享查询”赛题基于隐语实现baseline](https://mp.weixin.qq.com/s/ZXjC88VH0CQlt31E0WVvZw)

**Comment by meisir5648** [comment]
> 

和这个应该是没有关系的。我是在测max_label_length的最大取值。你们官方的说法是1000Bytes，但是这个值当我给到900时（我对应的label长度也有那么多），初始化setup没有问题，当建立链接发起查询时就报这个错误。

**Comment by Chrisdehe** [comment]
@meisir5648
这是一个已知的问题，可以参考下这条issue
https://github.com/secretflow/secretflow/issues/519

**Comment by meisir5648** [comment]
> @meisir5648 这是一个已知的问题，可以参考下这条issue [secretflow/secretflow#519](https://github.com/secretflow/secretflow/issues/519)

好的，谢谢。
