### ISSUE TITLE
编译失败，找不到bazel文件夹

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/spu#337]
spu版本为最新，系统环境为ubuntu20.04.
我在根目录运行python3 setup.py bdist_wheel进行编译。但是一直报错找不到bazel文件夹。

Traceback (most recent call last):
  File "setup.py", line 231, in <module>
    bazel_invoke(subprocess.check_call, ['clean'])
  File "setup.py", line 121, in bazel_invoke
    result = invoker(['bazel'] + cmdline, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bazel'

**Comment by zzx-QDU** [comment]
没有，我没有在Installation Guidelines看到这一要求。

**Comment by anakinxc** [comment]
Hi @zzx-QDU 

Check https://github.com/secretflow/spu/blob/main/CONTRIBUTING.md#linux

**Comment by zzx-QDU** [comment]
非常感谢。
