### ISSUE TITLE
[Bug]: spu 执行llama-7b  aby3失败（通信问题）

### ISSUE THREAD

**Issue by Daihongwei1900** [secretflow/spu#369]
### Issue Type

Usability

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

main(latest)

### OS Platform and Distribution

ubuntu22.04

### Python Version

3.10

### Compiler Version

11.4

### Current Behavior?

/home/zchain/mpc/spu/examples/python/ml/flax_gpt2   demo中，执行到spu5分钟后出现通信连接的问题

### Standalone code to reproduce the issue

```Python
按照llama-7b  demo 操作
配置文件
{
    "id": "outsourcing.3pc",
    "nodes": {
        "node:0": "127.0.0.1:9920",
        "node:1": "127.0.0.1:9921",
        "node:2": "127.0.0.1:9922",
        "node:3": "127.0.0.1:9923",
        "node:4": "127.0.0.1:9924"
    },
    "devices": {
        "SPU": {
            "kind": "SPU",
            "config": {
                "node_ids": [
                    "node:0",
                    "node:1",
                    "node:2"
                ],
                "spu_internal_addrs": [
                    "127.0.0.1:9930",
                    "127.0.0.1:9931",
                    "127.0.0.1:9932"
                ],
                "runtime_config": {
                    "protocol": "ABY3",
                    "field": "FM64",
                    "enable_pphlo_profile": true,
                    "enable_hal_profile": true,
                    "fxp_exp_mode": 1
                }
            }
        },
        "P1": {
            "kind": "PYU",
            "config": {
                "node_id": "node:3"
            }
        },
        "P2": {
            "kind": "PYU",
            "config": {
                "node_id": "node:4"
            }
        }
    }
}
```

### Relevant log output

```Shell
设备的日志：
[2023-10-16 20:37:06,314] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:07,773] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:08,285] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:08,797] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:10,286] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:10,800] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:10,801] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:12,809] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:13,325] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:13,838] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:15,431] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:15,435] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:16,779] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:16,780] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:16,784] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:18,100] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:22,545] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:23,887] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:25,216] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:30,704] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:32,049] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:33,366] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:37,861] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:37,864] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:38,378] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:38,382] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:38,921] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:38,925] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:40,569] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:41,082] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:41,577] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:43,195] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:43,720] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:44,231] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:45,774] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:46,286] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:46,784] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:48,396] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:48,400] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:49,744] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:49,745] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:49,748] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:51,073] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:55,485] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:56,832] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:37:58,169] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:03,120] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:04,462] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:04,462] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:10,304] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:10,308] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:10,822] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:10,825] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:11,357] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:11,368] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:12,903] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:13,419] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:13,926] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:15,506] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:16,017] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:16,514] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:18,167] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:18,675] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:19,185] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:20,813] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:20,817] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:22,158] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:22,158] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:22,162] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:23,489] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:27,935] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:29,123] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:29,992] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:33,396] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:34,067] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:34,067] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:38,240] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:38,243] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:38,538] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:38,545] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:38,958] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:38,962] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:40,375] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:40,764] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:40,764] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:42,771] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:43,179] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:43,524] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:45,103] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:45,507] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:45,852] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:47,400] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:47,403] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:48,595] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:48,596] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:48,599] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:49,902] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:53,447] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:54,175] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:54,176] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:58,578] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:59,315] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:38:59,316] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:03,386] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:03,388] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:03,797] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:03,803] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:04,084] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:04,114] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:04,824] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:05,142] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:05,420] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:06,443] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:06,721] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:07,000] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:08,116] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:08,388] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:08,648] [Process-5] RunR: builtin_fetch_object at node:4
[2023-10-16 20:39:20,261] [Process-1] Traceback (most recent call last):
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in Run
    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in <lambda>
    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 343, in _get_object
    obj = self._node_clients[ref.origin_nodeid].get(ref)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 261, in get
    return self._call(self._stub.RunReturn, builtin_fetch_object, ref.uuid)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "recvmsg:Connection reset by peer"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"recvmsg:Connection reset by peer", grpc_status:14, created_time:"2023-10-16T20:39:20.24528211+08:00"}"
>

[2023-10-16 20:39:20,261] [Process-3] Traceback (most recent call last):
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in Run
    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in <lambda>
    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 343, in _get_object
    obj = self._node_clients[ref.origin_nodeid].get(ref)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 261, in get
    return self._call(self._stub.RunReturn, builtin_fetch_object, ref.uuid)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "recvmsg:Connection reset by peer"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"recvmsg:Connection reset by peer", grpc_status:14, created_time:"2023-10-16T20:39:20.24528807+08:00"}"
>

[2023-10-16 20:39:20,262] [Process-2] Traceback (most recent call last):
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in Run
    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in <lambda>
    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 343, in _get_object
    obj = self._node_clients[ref.origin_nodeid].get(ref)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 261, in get
    return self._call(self._stub.RunReturn, builtin_fetch_object, ref.uuid)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "recvmsg:Connection reset by peer"
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"recvmsg:Connection reset by peer", grpc_status:14, created_time:"2023-10-16T20:39:20.250407445+08:00"}"
>

程序执行日志：
------
Run on SPU
Traceback (most recent call last):
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_llama7b/flax_llama7b.runfiles/spulib/examples/python/ml/flax_llama7b/flax_llama7b.py", line 180, in <module>
    outputs_ids = run_on_spu()
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_llama7b/flax_llama7b.runfiles/spulib/examples/python/ml/flax_llama7b/flax_llama7b.py", line 167, in run_on_spu
    outputs_ids = ppd.device("SPU")(text_generation, copts=copts)(input_ids, params)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_llama7b/flax_llama7b.runfiles/spulib/spu/utils/distributed.py", line 679, in __call__
    results = [future.result() for future in futures]
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_llama7b/flax_llama7b.runfiles/spulib/spu/utils/distributed.py", line 679, in <listcomp>
    results = [future.result() for future in futures]
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_llama7b/flax_llama7b.runfiles/spulib/spu/utils/distributed.py", line 249, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/flax_llama7b/flax_llama7b.runfiles/spulib/spu/utils/distributed.py", line 242, in _call
    raise Exception("remote exception", result)
Exception: ('remote exception', Exception('Traceback (most recent call last):\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in Run\n    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))\n  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in tree_map\n    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))\n  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/jax/_src/tree_util.py", line 210, in <genexpr>\n    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 323, in <lambda>\n    args, kwargs = tree_map(lambda obj: self._get_object(obj), (args, kwargs))\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 343, in _get_object\n    obj = self._node_clients[ref.origin_nodeid].get(ref)\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 261, in get\n    return self._call(self._stub.RunReturn, builtin_fetch_object, ref.uuid)\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in _call\n    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in rebuild_messages\n    return b\'\'.join([msg for msg in msgs])\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 218, in <listcomp>\n    return b\'\'.join([msg for msg in msgs])\n  File "/home/zchain/.cache/bazel/_bazel_zchain/c9f8500959909f2bce699464008a4b32/execroot/spulib/bazel-out/k8-opt/bin/examples/python/utils/nodectl.runfiles/spulib/spu/utils/distributed.py", line 238, in <genexpr>\n    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)\n  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 541, in __next__\n    return self._next()\n  File "/home/zchain/mpc/spu/venv/lib/python3.10/site-packages/grpc/_channel.py", line 967, in _next\n    raise self\ngrpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "recvmsg:Connection reset by peer"\n\tdebug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"recvmsg:Connection reset by peer", grpc_status:14, created_time:"2023-10-16T20:39:20.24528211+08:00"}"\n>\n'))
```

**Comment by anakinxc** [comment]
请问一下你这边机器配置

**Comment by Daihongwei1900** [comment]
> 请问一下你这边机器配置

112  核 500G 内存  Intel(R) Xeon(R) Gold 6330N CPU @ 2.20GHz

**Comment by anakinxc** [comment]
> > 请问一下你这边机器配置
> 
> 112 核 500G 内存 Intel(R) Xeon(R) Gold 6330N CPU @ 2.20GHz

跑 llama7b 的话每个节点需要 1tb 内存，也就是说如果在一台机器上跑三个节点，你需要 大概 3tb 的内存才行
