### ISSUE TITLE
bazel build报错

### ISSUE THREAD

**Issue by xiaoqing928** [secretflow/spu#381]
### Issue Type

Build/Install

### Source

binary

### Secretflow Version

0.6

### OS Platform and Distribution

centos7

### Python version

3.8

### What happend and What you expected to happen.

```shell
使用bazel build c++项目时，找不到外部yacl库，请问该如何解决？
```

### Reproduction code to reproduce the issue.

```shell
(base) [app@localhost cpp]$ bazel build //examples/cpp:simple_psi
Starting local Bazel server and connecting to it...
INFO: Repository yacl instantiated at:
  /data/projects/install/spu-main/WORKSPACE:19:9: in <toplevel>
  /data/projects/install/spu-main/bazel/repositories.bzl:44:10: in spu_deps
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule git_repository defined at:
  /home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl:181:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'yacl':
   Traceback (most recent call last):
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
		update = _clone_or_update_repo(ctx)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
		git_ = git_repo(ctx, directory)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 109, column 10, in _update
		fetch(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 143, column 13, in fetch
		_git(
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 179, column 15, in _git
		_error(ctx.name, start + list(args), st.stderr)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @yacl:
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
ERROR: /data/projects/install/spu-main/WORKSPACE:19:9: fetching git_repository rule //external:yacl: Traceback (most recent call last):
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 175, column 35, in _git_repository_implementation
		update = _clone_or_update_repo(ctx)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update_repo
		git_ = git_repo(ctx, directory)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 109, column 10, in _update
		fetch(ctx, git_repo)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 143, column 13, in fetch
		_git(
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 179, column 15, in _git
		_error(ctx.name, start + list(args), st.stderr)
	File "/home/app/.cache/bazel/_bazel_app/66e006088071ef6b9cf60a86b45c01e0/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 200, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @yacl:
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
ERROR: Error computing the main repository mapping: no such package '@yacl//bazel': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @yacl:
error: RPC failed; result=7, HTTP code = 0
fatal: The remote end hung up unexpectedly
```

**Comment by anakinxc** [comment]
> 1、首次在spu（workspace）路径下执行bazel build //examples/cpp:simple_psi，编译成功后，在当前目录下分别起两个终端执行./bazel-bin/examples/cpp/simple_psi -rank 1 -protocol 1 -in_path ./examples/data/psi_2.csv -field_names id -out_path /tmp/p2.out（两个终端的参数稍有差异） 2、修改了spu/libspu/psi路径下的bucket_psi.cc文件，照猫画虎加了几行日志输出，详情如下： MemoryPsiConfig config; config.set_psi_type(config_.psi_type()); SPDLOG_INFO("psi_type set to {}", config_.psi_type()); config.set_curve_type(config_.curve_type()); SPDLOG_INFO("curve_type set to {}", config_.curve_type()); config.set_receiver_rank(config_.receiver_rank()); SPDLOG_INFO("receiver_rank set to {}", config_.receiver_rank()); config.set_broadcast_result(config_.broadcast_result()); SPDLOG_INFO("broadcast_result set to {}", config_.broadcast_result()); 3、再次执行步骤1，发现修改的没有生效

应该是可以 work 的，我本地试了一下是没问题的，麻烦确认一下修改好的 bazel build 成功了

**Comment by xiaoqing928** [comment]
好的，我再试试。另外，为什么每次bazel build时，执行到ipp阶段耗时非常久呢？

**Comment by xiaoqing928** [comment]
我又尝试了下，确实是work的。
下午重新bazel build的时候，在ipp阶段仍然编译了好久，我还觉得很奇怪。
刚刚重新试了下，build的很快，修改内容也生效了，感谢感谢！！

**Comment by anakinxc** [comment]
> 我又尝试了下，确实是work的。 下午重新bazel build的时候，在ipp阶段仍然编译了好久，我还觉得很奇怪。 刚刚重新试了下，build的很快，修改内容也生效了，感谢感谢！！

bazel 有自己的 cache 机制，但是环境变量出现变化容易 rebuild
