### ISSUE TITLE
spu编译错误

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/spu#395]
### Issue Type

Build/Install

### Modules Involved

PSI

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu0.5

### OS Platform and Distribution

Ubuntu 20.04.6 LTS（windows上安装的wsl，64位操作系统）

### Python Version

3.9.13

### Compiler Version

gcc11

### Current Behavior?

bazel build出错

### Standalone code to reproduce the issue

```Python
bazel build出错
```

### Relevant log output

```Shell
lishihao@lishihao:~/spu-main$ bazel build //examples/cpp:simple_psi
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/xla/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'tf_runtime' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/xla/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'llvm-raw' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'com_github_grpc_grpc' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'upb' because it already exists.
INFO: Repository go_sdk instantiated at:
  /home/lishihao/spu-main/WORKSPACE:65:15: in <toplevel>
  /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/xla/workspace0.bzl:52:19: in workspace
  /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/tsl/workspace0.bzl:130:20: in workspace
  /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:56:27: in grpc_extra_deps
  /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/io_bazel_rules_go/go/private/sdk.bzl:424:24: in go_register_toolchains
  /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/io_bazel_rules_go/go/private/sdk.bzl:42:17: in go_host_sdk
Repository rule _go_host_sdk defined at:
  /home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/io_bazel_rules_go/go/private/sdk.bzl:36:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
        File "/home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/io_bazel_rules_go/go/private/sdk.bzl", line 31, column 30, in _go_host_sdk_impl
                goroot = _detect_host_sdk(ctx)
        File "/home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/io_bazel_rules_go/go/private/sdk.bzl", line 301, column 13, in _detect_host_sdk
                fail("Could not detect host go version")
Error in fail: Could not detect host go version
ERROR: /home/lishihao/spu-main/WORKSPACE:65:15: fetching _go_host_sdk rule //external:go_sdk: Traceback (most recent call last):
        File "/home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/io_bazel_rules_go/go/private/sdk.bzl", line 31, column 30, in _go_host_sdk_impl
                goroot = _detect_host_sdk(ctx)
        File "/home/lishihao/.cache/bazel/_bazel_lishihao/b085e7ccdf3e4fc101751f695c05d80b/external/io_bazel_rules_go/go/private/sdk.bzl", line 301, column 13, in _detect_host_sdk
                fail("Could not detect host go version")
Error in fail: Could not detect host go version
ERROR: Analysis of target '//examples/cpp:simple_psi' failed; build aborted: Could not detect host go version
INFO: Elapsed time: 12.870s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 9 targets configured)
    Fetching repository @local_execution_config_python; starting
    Fetching repository @local_cuda; starting
    Fetching repository @local_config_python; starting
```

**Comment by anakinxc** [comment]
Hi @daydayuphere 

编译 0.5.0 的话，安装一下 golang。HEAD 的话就不需要了

**Comment by daydayuphere** [comment]
请问head是哪个版本

**Comment by anakinxc** [comment]
https://github.com/secretflow/spu/commit/b0674fdad3247995c078df93e377acf854d933f1
