### ISSUE TITLE
[Bug]: 运行llama的toturial出错

### ISSUE THREAD

**Issue by gystar** [secretflow/spu#403]
### Issue Type

Build/Install

### Modules Involved

Documentation/Tutorial/Example

### Current Behavior?

在尝试复现llama实验时，使用原有教程中的llama仓库有问题，因此按照[Issue365](https://github.com/secretflow/spu/issues/365)中的解决方法：
`
python3 -m EasyLM.scripts.convert_checkpoint --load_checkpoint='params::/xxx/open_llama_7b_easylm/open_llama_7b_easylm' --output_file='/xxx/spu/llama-7b.msgpack' --streaming=False
`
结果报错（注意gpt-2的example已经可以跑通）：
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/spu/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/xxx/miniconda3/envs/spu/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/xxx/projects/EasyLM/EasyLM/scripts/convert_checkpoint.py", line 42, in <module>
    mlxu.run(main)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/xxx/projects/EasyLM/EasyLM/scripts/convert_checkpoint.py", line 37, in main
    with mlxu.open_file(FLAGS.output, 'wb') as fout:
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/absl/flags/_flagvalues.py", line 474, in __getattr__
    raise AttributeError(name)
AttributeError: output

**Comment by tpppppub** [comment]
@Ye-D @llCurious any idea?

**Comment by Ye-D** [comment]
@gystar Test the following solution:
change 
`File "/xxx/projects/EasyLM/EasyLM/scripts/convert_checkpoint.py", line 37, in main
with mlxu.open_file(FLAGS.output, 'wb') as fout:`
as
`with mlxu.open_file(FLAGS.output_file, 'wb') as fout:`

**Comment by gystar** [comment]
应该是这个examples/python/ml/flax_llama7b/README.md中有问题，参考中的examples/python/ml/flax_llama7b_split/README.md中：
`python3 convert_hf_to_easylm.py --checkpoint_dir=/xxx/projects/open_llama_7b --output_file=/xxx/projects/spu/llama-7b.msgpack --model_size 7b --streaming`
可以正常完成，这里的llama的weight可以有多个。

**Comment by gystar** [comment]
@tpppppub @Ye-D 但是继续运行examples/python/ml/flax_llama7b/README.md中的教程还是有问题，能否完善一下？
其中
    ```sh
    cd path_to_EasyLM/EasyLM/models/llama
    python convert_hf_to_easylm.py  \
       --checkpoint_dir     path_to_llama_weights    \
       --output_file path_to_outputfile  \
       --model_size 7b \
       --streaming
    ```
这一步将原有的llama成功进行了转换，转换后的问题件放在哪里呢？后面步骤也没有用到，是否遗漏了？
    Move the python file to EasyLM if you do not use the fork fork created for transformer split.

    ```sh
    cp path-to-llama_model_split_transformer_py path_to_EasyLM/EasyLM/models/llama
    ```
我没有使用fork分支的方法因此cp的这个py文件到path_to_EasyLM/EasyLM/models/llama，然而运行下面的步骤出错：
4. Run `flax_llama7b_split` example

    ```sh
    bazel run -c opt //examples/python/ml/flax_llama7b_split -- --config `pwd`/examples/python/ml/flax_llama7b_split/3pc.json
    ```

    or（recommended）

    ```sh
    cd examples/python/ml/flax_llama7b_split
    python

**Comment by Ye-D** [comment]
run
`cd EasyLM
export PYTHONPATH="${PWD}:$PYTHONPATH"`
to add EasyLM

**Comment by gystar** [comment]
转换之后的模型文件应该放在哪里呢，后面没有看到指定这个模型的参数

**Comment by tpppppub** [comment]
这个需要修改源文件 [flax_llama7b.py](https://github.com/secretflow/spu/blob/main/examples/python/ml/flax_llama7b/flax_llama7b.py#L52)，指定模型和 tokenizer 路径。这里文档确实还不太完善，会进行补充，也欢迎直接提交 PR 修改

**Comment by gystar** [comment]
@tpppppub 好的 我修改一下文档提交一个pr把 包括另外一个非spilt版本的 我会test一下再提交哈

**Comment by gystar** [comment]
@tpppppub @Ye-D 
指定了模型和tokenizer的路径之后，运行的时候还是会报错：
Traceback (most recent call last):
  File "flax_llama7b_split.py", line 63, in <module>
    ppd.init(conf["nodes"], conf["devices"])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 1110, in init
    _CONTEXT = HostContext(nodes_def, devices_def)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 1037, in __init__
    self.devices[name] = SPU(
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 952, in __init__
    results = [future.result() for future in futures]
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 952, in <listcomp>
    results = [future.result() for future in futures]
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 249, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 238, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 218, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 218, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 238, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:7890: recvmsg:Connection reset by peer"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:7890: recvmsg:Connection reset by peer {created_time:"2023-11-16T14:44:14.385993898+08:00", grpc_status:14}"

这个7890是我本地代理的端口，就算我去掉代理，还是会提示我另外一个端口错误。

**Comment by tpppppub** [comment]
麻烦说明一下运行步骤以及 3pc.json 配置文件。另外为什么这里要使用本地代理的端口？

**Comment by gystar** [comment]
按照examples/python/ml/flax_llama7b_split/README.md的说明进行配置，运行到最后一步（第4步），使用的是库里面examples/python/ml/flax_llama7b_split/3pc.json的配置文件，没有修改。
使用bazel或者直接运行那个py文件都会出现同样的错误
就算我把本地代理关掉，还是会显示我其它程序本地已经暂用的端口。

**Comment by gystar** [comment]
@tpppppub 补充一下，GPT2的例子是可以正常跑完的

**Comment by tpppppub** [comment]
运行第三步的终端里的日志是什么？

**Comment by tpppppub** [comment]
另外请问下你的服务器配置，llama 的例子对服务器内存要求比较高

**Comment by gystar** [comment]
![image](https://github.com/secretflow/spu/assets/10754127/7ea2a97b-9d16-44c7-85e8-c861c87f8f36)
重新run了一遍，又可以了~

**Comment by gystar** [comment]
> 另外请问下你的服务器配置，llama 的例子对服务器内存要求比较高

对了，关于这个问题，我想请教一下您。
能否只把input给SPU，模型不加密，这样能省下很多内存？
要如何做呢？

**Comment by tpppppub** [comment]
可以不加密模型，把 `run_on_spu` 里的 `params = ppd.device("P2")(lambda x: x)(pretrained_model.params)` 改成 `params = pretrained_model.params` 即可。但模型参数是各方公开可见的，这个安全模型意义不大。

**Comment by gystar** [comment]
> 可以不加密模型，把 `run_on_spu` 里的 `params = ppd.device("P2")(lambda x: x)(pretrained_model.params)` 改成 `params = pretrained_model.params` 即可。但模型参数是各方公开可见的，这个安全模型意义不大。

关于这点我有些不太理解额，我想的是把input传给model方，将计算好了将加密的结果传送回来即可，这样子model方应该不用加密自己的模型吧？

**Comment by tpppppub** [comment]
你说的是同态加密的典型场景，在 MPC 里，需要数据持有者与计算方是同一方的 [colocated](https://www.secretflow.org.cn/docs/spu/latest/en-US/development/runtime#colocated) 模式 + 协议层支持相应的 private 算子（数据只对一方可见）才行。目前在这些例子里是不支持的。

**Comment by gystar** [comment]
> tpppppub

@tpppppub 关于这种方式，能否再请教一下您呢，我正在做一些研究工作，可以一起合作，应该不会占用多少时间的。
我的邮箱guiyi@hust.edu.cn
