### ISSUE TITLE
[Bug]: 运行一段时间之后无法连接上端口模拟进程server

### ISSUE THREAD

**Issue by gystar** [secretflow/spu#421]
**1.我在一个Robert模型上使用SPU进行分类任务（非text generation）的inference，会循环跑很多个数据点。但是跑几十个数据点之后就会很容易在client端（model inference端）报错：**
Traceback (most recent call last):
  File "roberta.py", line 114, in <module>
    pre = run_on_spu(inputs_ids, PRETRAINED_MODEL.params)
  File "roberta.py", line 59, in run_on_spu
    outputs = ppd.device("SPU")(
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 679, in __call__
    results = [future.result() for future in futures]
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 679, in <listcomp>
    results = [future.result() for future in futures]
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 249, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 238, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 218, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 218, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 238, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/grpc/_channel.py", line 967, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-11-27T21:18:41.065482153+08:00"}"

**2.同时在server端（端口模拟端）会报错：**

[2023-11-27 21:15:33.074] [[32minfo[m] [api.cc:204] Link details: total send bytes 4412083004, send actions 25207
W1127 21:18:40.795603 3191480 external/com_github_brpc_brpc/src/brpc/input_messenger.cpp:375] Fail to read from Socket{id=0 fd=17 addr=127.0.0.1:9930:35130} (0x7fae24068280): Connection reset by peer
I1127 21:18:40.895106 3191540 external/com_github_brpc_brpc/src/brpc/socket.cpp:2466] Checking Socket{id=0 addr=127.0.0.1:9930} (0x7fae20068280)
I1127 21:18:40.905504 3191551 external/com_github_brpc_brpc/src/brpc/socket.cpp:2466] Checking Socket{id=0 addr=127.0.0.1:9930} (0x7fae24068280)
[2023-11-27 21:18:41.428] [[32minfo[m] [channel.cc:346] send request failed and retry, retry_count=1, max_retry=3, interval_ms=1000, message=[external/yacl/yacl/link/transport/interconnection_link.cc:56] cntl ErrorCode '104', http status code '0', response header '', response body '', error msg '[E104]Fail to read from Socket{id=0 fd=17 addr=127.0.0.1:9930:35130} (0x0x7fae24068280): Connection reset by peer'
Stacktrace:
#0 yacl::link::transport::BrpcLink::SendRequest()+0x7faece344ed0
#1 yacl::link::transport::Channel::SendRequestWithRetry()+0x7faece358639
#2 yacl::link::transport::Channel::SendMono()+0x7faece358987
#3 yacl::link::transport::SendTask::Proc()+0x7faece35ba72
#4 bthread::TaskGroup::task_runner()+0x7faece4dce17
#5 bthread_make_fcontext+0x7faece4f1d71
......
[2023-11-27 21:18:45.440] [[32minfo[m] [channel.cc:346] send request failed and retry, retry_count=3, max_retry=3, interval_ms=5000, message=[external/yacl/yacl/link/transport/interconnection_link.cc:56] cntl ErrorCode '112', http status code '0', response header '', response body '', error msg '[E112]Not connected to 127.0.0.1:9930 yet, server_id=0'
Stacktrace:
#0 yacl::link::transport::BrpcLink::SendRequest()+0x7faece344ed0
#1 yacl::link::transport::Channel::SendRequestWithRetry()+0x7faece358639
#2 yacl::link::transport::Channel::SendMono()+0x7faece358987
#3 yacl::link::transport::SendTask::Proc()+0x7faece35ba72
#4 bthread::TaskGroup::task_runner()+0x7faece4dce17
#5 bthread_make_fcontext+0x7faece4f1d71

[2023-11-27 21:18:50.451] [[31m[1merror[m] [channel.cc:98] SendImpl error [external/yacl/yacl/link/transport/interconnection_link.cc:56] cntl ErrorCode '112', http status code '0', response header '', response body '', error msg '[E112]Not connected to 127.0.0.1:9930 yet, server_id=0'
Stacktrace:
#0 yacl::link::transport::BrpcLink::SendRequest()+0x7faece344ed0
#1 yacl::link::transport::Channel::SendRequestWithRetry()+0x7faece358639
#2 yacl::link::transport::Channel::SendMono()+0x7faece358987
#3 yacl::link::transport::SendTask::Proc()+0x7faece35ba72
#4 bthread::TaskGroup::task_runner()+0x7faece4dce17
#5 bthread_make_fcontext+0x7faece4f1d71

[2023-11-27 21:18:50.451] [[31m[1merror[m] [channel.cc:98] SendImpl error [external/yacl/yacl/link/transport/interconnection_link.cc:56] cntl ErrorCode '112', http status code '0', response header '', response body '', error msg '[E112]Not connected to 127.0.0.1:9930 yet, server_id=0'
Stacktrace:
#0 yacl::link::transport::BrpcLink::SendRequest()+0x7faece344ed0
#1 yacl::link::transport::Channel::SendRequestWithRetry()+0x7faece358639
#2 yacl::link::transport::Channel::SendMono()+0x7faece358987
#3 yacl::link::transport::SendTask::Proc()+0x7faece35ba72
#4 bthread::TaskGroup::task_runner()+0x7faece4dce17
#5 bthread_make_fcontext+0x7faece4f1d71

[2023-11-27 21:18:50.452] [[31m[1merror[m] [channel.cc:98] SendImpl error [external/yacl/yacl/link/transport/interconnection_link.cc:56] cntl ErrorCode '112', http status code '0', response header '', response body '', error msg '[E112]Not connected to 127.0.0.1:9930 yet, server_id=0'
Stacktrace:
#0 yacl::link::transport::BrpcLink::SendRequest()+0x7faece344ed0
#1 yacl::link::transport::Channel::SendRequestWithRetry()+0x7faece358639
#2 yacl::link::transport::Channel::SendMono()+0x7faece358987
#3 yacl::link::transport::SendTask::Proc()+0x7faece35ba72
#4 bthread::TaskGroup::task_runner()+0x7faece4dce17
#5 bthread_make_fcontext+0x7faece4f1d71

I1127 21:18:51.702651 3191492 external/com_github_brpc_brpc/src/brpc/socket.cpp:2466] Checking Socket{id=1 addr=127.0.0.1:9931} (0x7fae20068500)
terminate called after throwing an instance of 'yacl::IoError'
  what():  [external/yacl/yacl/link/transport/channel.cc:405] Get data timeout, key=root-176919:P2P-1:0->2
Stacktrace:
#0 yacl::link::Context::RecvInternal()+0x7faece34f99b
#1 yacl::link::Context::Recv()+0x7faece351e06
#2 spu::mpc::Communicator::rotate()+0x7faecdf9eda5
#3 spu::mpc::aby3::MatMulAA::proc()+0x7faecd68c54b
#4 spu::dynDispatch<>()+0x7faecdfe7708
#5 spu::mpc::mmul_aa()+0x7faecdffcf45
#6 spu::mpc::mmul_ss()+0x7faecdfef909
#7 spu::kernel::hal::_mmul_ss()+0x7faecdfdb86b
#8 spu::kernel::hal::_mmul_impl()+0x7faecdfc80a2
#9 spu::kernel::hal::_mmul()+0x7faecdfcdf6e
#10 spu::kernel::hal::f_mmul()+0x7faecdf63390
#11 spu::kernel::hal::(anonymous namespace)::dtypeBinaryDispatch<>()+0x7faecdf4ba4c
#12 spu::kernel::hal::matmul()+0x7faecdf4c49d
#13 spu::kernel::hlo::Dot()+0x7faecdf3030f
#14 spu::device::pphlo::dispatchOp<>()+0x7faecd911a2c
#15 spu::device::pphlo::dispatchOp<>()+0x7faecd913e9c

Process Process-4:
Traceback (most recent call last):
  File "nodectl.py", line 57, in <module>
    worker.join()
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/process.py", line 149, in join
^C  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 224, in __call__
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 464, in close_fds
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 224, in __call__
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 464, in close_fds
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 224, in __call__
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 464, in close_fds
AttributeError: 'NoneType' object has no attribute 'close'
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 224, in __call__
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/multiprocess/util.py", line 464, in close_fds
AttributeError: 'NoneType' object has no attribute 'close'

 **3.不重启server的情况下，再使用client必定失败；重启server，从失败的datapoint开始，又能正常运行几十个datapoint。 若不重启server，client会报错：**

Traceback (most recent call last):
  File "roberta.py", line 87, in <module>
    ppd.init(conf["nodes"], conf["devices"])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 1110, in init
    _CONTEXT = HostContext(nodes_def, devices_def)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 1037, in __init__
    self.devices[name] = SPU(
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 952, in __init__
    results = [future.result() for future in futures]
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 952, in <listcomp>
    results = [future.result() for future in futures]
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/xxx/miniconda3/envs/spu/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 249, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 238, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 218, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 218, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 238, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/grpc/_channel.py", line 541, in __next__
    return self._next()
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/grpc/_channel.py", line 950, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:9920: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:9920: Failed to connect to remote host: Connection refused {grpc_status:14, created_time:"2023-11-28T08:47:33.462023675+08:00"}"

**Comment by tpppppub** [comment]
可能是内存不足导致程序崩了，建议先小数据量小模型验证下程序正确性

**Comment by gystar** [comment]
经过验证，我换了一个128G的主机，经过长时间的运行从之前64G内存的跑20个的datapoint到现在能跑200个datapoint左右，发现内存一直在缓慢增加，我看过自己的程序，里面没有增加内存的list等结构，怀疑可能是server存在内存泄露。

**Comment by tpppppub** [comment]
能提供下代码吗？我们好复现一下

**Comment by gystar** [comment]
这是我统计的内存log，每次跑完一次inference进行统计，可以看到client的内存每次几乎没有变化，但是总的使用内存一直在增加：
0it [00:00, ?it/s]total free mem 37.20, mem of current process 0.03
1it [02:25, 145.40s/it]total free mem 44.40, mem of current process 0.03
2it [05:01, 151.45s/it]total free mem 47.20, mem of current process 0.03
3it [07:21, 146.42s/it]total free mem 53.20, mem of current process 0.03
4it [09:42, 144.39s/it]total free mem 58.20, mem of current process 0.03
5it [12:13, 146.60s/it]total free mem 61.50, mem of current process 0.03
然后使用ps命令能看到server相关进行的内存持续增加了很多：
               total        used        free      shared  buff/cache   available
Mem:           62Gi        38Gi        17Gi        32Mi       7.1Gi        23Gi
Swap:         9.5Gi          0B       9.5Gi
 pid     ppid    %mem
 # spu server:
 121843   30363  0.1
 121870  121843 13.6
 121872  121843 13.2
 121874  121843 13.0
 121876  121843  0.1
 121878  121843 14.0
                54.0
 # model inference: 
 122119   31189  3.0

**Comment by gystar** [comment]
> 能提供下代码吗？我们好复现一下

代码发你同事了

**Comment by warriorpaw** [comment]
distributed本身是一个性能测试使用的框架，为了性能效果，会根据堆积的对象个数延迟执行GC操作。
如果每次跑都加载一次模型，那么这些模型就会堆积到待删除的队列里，并且你这个模型很大，所以看起来像是内存泄漏。

换个写法，模型加载一次重复使用，就可以了，diff如下


```
--- /Users/paw/Desktop/1/test.py	Mon Nov 27 10:46:58 2023
+++ /Users/paw/Desktop/1/test_2.py	Wed Nov 29 11:14:19 2023
@@ -60,13 +60,12 @@
     return df.func.tolist(), df.target.tolist()
 
 
-def run_on_spu(inputs_ids):
+def run_on_spu(inputs_ids, spu_params):
     # encode context the generation is conditioned
     input_ids = ppd.device("P1")(lambda x: x)(inputs_ids)
-    params = ppd.device("P2")(lambda x: x)(pretrained_model.params)
     outputs = ppd.device("SPU")(
         text_classification,
-    )(input_ids, params)
+    )(input_ids, spu_params)
 
     outputs = ppd.get(outputs)
     return outputs
@@ -103,6 +102,8 @@
     pre_spu = []
     time_cpu = 0
     time_spu = 0
+    spu_params = ppd.Device.move(ppd.device("P2")(lambda x: x)(pretrained_model.params), ppd.device("SPU"))
     for n,(func, label) in tqdm.tqdm(enumerate (zip(funcs, labels))):
         LOGGER.info(f"-------processing [ {n+1+resume_from}/{len(funcs)+resume_from} ]\n")
         inputs_ids = tokenizer.encode(func, return_tensors="jax")
@@ -117,7 +118,7 @@
         LOGGER.info(f"duration {t2 - t1}, res {pre}")
 
         LOGGER.info("\n------\nRun on SPU")        
-        pre = run_on_spu(inputs_ids)
+        pre = run_on_spu(inputs_ids, spu_params)
         pre_spu.append(bool(pre))
         t3 = time.time()
         time_spu += t3 - t2
```

**Comment by gystar** [comment]
> distributed本身是一个性能测试使用的框架，为了性能效果，会根据堆积的对象个数延迟执行GC操作。 如果每次跑都加载一次模型，那么这些模型就会堆积到待删除的队列里，并且你这个模型很大，所以看起来像是内存泄漏。
> 
> 换个写法，模型加载一次重复使用，就可以了，diff如下
> 
> ```
> --- /Users/paw/Desktop/1/test.py	Mon Nov 27 10:46:58 2023
> +++ /Users/paw/Desktop/1/test_2.py	Wed Nov 29 11:14:19 2023
> @@ -60,13 +60,12 @@
>      return df.func.tolist(), df.target.tolist()
>  
>  
> -def run_on_spu(inputs_ids):
> +def run_on_spu(inputs_ids, spu_params):
>      # encode context the generation is conditioned
>      input_ids = ppd.device("P1")(lambda x: x)(inputs_ids)
> -    params = ppd.device("P2")(lambda x: x)(pretrained_model.params)
>      outputs = ppd.device("SPU")(
>          text_classification,
> -    )(input_ids, params)
> +    )(input_ids, spu_params)
>  
>      outputs = ppd.get(outputs)
>      return outputs
> @@ -103,6 +102,8 @@
>      pre_spu = []
>      time_cpu = 0
>      time_spu = 0
> +    spu_params = ppd.Device.move(ppd.device("P2")(lambda x: x)(pretrained_model.params), ppd.device("SPU"))
>      for n,(func, label) in tqdm.tqdm(enumerate (zip(funcs, labels))):
>          LOGGER.info(f"-------processing [ {n+1+resume_from}/{len(funcs)+resume_from} ]\n")
>          inputs_ids = tokenizer.encode(func, return_tensors="jax")
> @@ -117,7 +118,7 @@
>          LOGGER.info(f"duration {t2 - t1}, res {pre}")
>  
>          LOGGER.info("\n------\nRun on SPU")        
> -        pre = run_on_spu(inputs_ids)
> +        pre = run_on_spu(inputs_ids, spu_params)
>          pre_spu.append(bool(pre))
>          t3 = time.time()
>          time_spu += t3 - t2
> ```

改了之后代码报错：
  File "roberta.py", line 110, in <module>
    spu_model_params = ppd.Device.move(ppd.device("P2")(lambda x: x)(PRETRAINED_MODEL.params), ppd.device("SPU"))
  File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 449, in move
    move_fn = Device.TRANS_KERNELS[obj.device.__class__, dest.__class__]
AttributeError: 'dict' object has no attribute 'device'

**Comment by gystar** [comment]
@warriorpaw ， 改了之后会报错：
Traceback (most recent call last):
  File "roberta.py", line 110, in <module>
    spu_model_params = ppd.Device.move(ppd.device("P2")(lambda x: x)(PRETRAINED_MODEL.params), ppd.device("SPU"))
  File "/data/gy/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 449, in move
    move_fn = Device.TRANS_KERNELS[obj.device.__class__, dest.__class__]
AttributeError: 'dict' object has no attribute 'device'

**Comment by warriorpaw** [comment]
> @warriorpaw ， 改了之后会报错： Traceback (most recent call last): File "roberta.py", line 110, in spu_model_params = ppd.Device.move(ppd.device("P2")(lambda x: x)(PRETRAINED_MODEL.params), ppd.device("SPU")) File "/xxx/miniconda3/envs/spu/lib/python3.8/site-packages/spu/utils/distributed.py", line 449, in move move_fn = Device.TRANS_KERNELS[obj.device.**class**, dest.**class**] AttributeError: 'dict' object has no attribute 'device'

报错的那句换成

spu_params = ppd.device("SPU")._place_arguments(ppd.device("P2")(lambda x: x)(PRETRAINED_MODEL.params))[0][0]

**Comment by gystar** [comment]
@warriorpaw 经过修改，内存状况如下：
0it [00:00, ?it/s]total used mem 80.80, mem of current process 0.03
1it [02:01, 121.06s/it]total used mem 86.20, mem of current process 0.03
2it [04:02, 121.17s/it]total used mem 90.00, mem of current process 0.03
3it [05:47, 113.70s/it]total used mem 90.90, mem of current process 0.03
4it [07:35, 111.41s/it]total used mem 90.80, mem of current process 0.03
5it [09:35, 114.65s/it]total used mem 91.20, mem of current process 0.03

可以发现模型参数相当于一直没有释放，一开始内存就会很高，然而内存还是会缓慢增加。从之前的分析可以得出：
1.重复加载model可能导致有内存没有释放结束，导致“内存泄露”
2.那么一直不断的加载input_id是否也存在此问题呢？也就是造成内存还是不断增加的隐患？
3.能否主动调用GC来进行释放？

**Comment by gystar** [comment]
@warriorpaw 我把_GC_COLLECT_THRESHOLD 从默认的50改成30之后，内存满的速度更快了。。。本来是能跑4小时左右才满，现在2小时不到。。。。
![image](https://github.com/secretflow/spu/assets/10754127/8e5fefe1-32d3-488e-a725-9990586f0291)

**Comment by gystar** [comment]
> 无法复现你描述的问题，跑你提供的代码超过12个小时 总计418个迭代，最终内存占用没有超过35GB。测试过程中内存占用有略微增长，可能原因是 malloc 内部未释放碎片导致，但是没看到你描述的快速增长占用超过120+GB的情况。
> 
> 麻烦提供下系统htop对比截图：刚运行第一个迭代和占用增长到100+GB时的截图，需要能看出来哪些进程增加的占用。感谢

我私下给你一个阿里云环境，这是必现的问题。

**Comment by gystar** [comment]
经过在另外两台ubuntu22.04上运行，可以持续跑循环，估计是ubuntu20.04系统glibc malloc的问题了。可以尝试一下方法解决：
安装gperf
sudo apt-get install google-perftools
export LD_PRELOAD=libtcmalloc.so.4
