### ISSUE TITLE
simulation中pps.sim_jax的static_argnums参数如何使用？

### ISSUE THREAD

**Issue by oahcnauygnid** [secretflow/spu#45]
当我运行这样一段代码时，有报错信息：
```python
import jax
import jax.numpy as jnp
import spu
import spu.binding.util.simulation as pps

protocol = spu.ProtocolKind.ABY3
field = spu.FieldType.FM128
config = spu.RuntimeConfig(protocol=protocol, field=field)
config.enable_pphlo_profile = True
config.enable_action_trace = True
simulator = pps.Simulator(3, config)

def test_add(x, y, x0=20, y0=30):
    return x + x0, y + y0

if __name__ == "__main__":
    spu_test_add = pps.sim_jax(simulator,test_add,static_argnums=(2,3))
    x = 0
    y = 10
    x1, y1 = spu_test_add(x,y,20,30)
```   
报错信息为：
```text
Traceback (most recent call last):
  File "**/sim.py", line 21, in <module>
    x1, y1 = spu_test_add(x,y,20,30)
  File "**/python3.8/site-packages/spu/binding/util/simulation.py", line 128, in wrapper
    f, dyn_args = japi_util.argnums_partial_except(
  File "**/python3.8/site-packages/jax/_src/api_util.py", line 180, in argnums_partial_except
    return _argnums_partial(f, dyn_argnums, tuple(fixed_args)), dyn_args
  File "**/python3.8/site-packages/jax/linear_util.py", line 219, in transformation
    return fun.wrap(gen, gen_static_args, None)
AttributeError: 'function' object has no attribute 'wrap'
```
我尝试跟踪了下报错信息，但没清楚一个函数的wrap函数是怎么来的

**Comment by 6fj** [comment]
Hi @oahcnauygnid 

1. 你这里并不需要static_argnums。
2. static_argnums似乎已经break了，感谢指出，我们将会尽快fix。

**Comment by anakinxc** [comment]
Fixed #47
