### ISSUE TITLE
Error in Running Python example millionare.py and script build_and_packaging.sh

### ISSUE THREAD

**Issue by DuanYuFi** [secretflow/spu#52]
Hi, I am using the official docker image and installed spu from pypi with version 0.3.0. Now I am trying to run the examples/python/millionare.py that provided in the repo. But I got the error log:

```
Traceback (most recent call last):
  File "millionare.py", line 39, in <module>
    ppd.init(conf["nodes"], conf["devices"])
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 1099, in init
    _CONTEXT = HostContext(nodes_def, devices_def)
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 1026, in __init__
    self.devices[name] = SPU(
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 941, in __init__
    results = [future.result() for future in futures]
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 941, in <listcomp>
    results = [future.result() for future in futures]
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 251, in run
    return self._call(self._stub.Run, fn, *args, **kwargs)
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 240, in _call
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 220, in rebuild_messages
    return b''.join([msg for msg in msgs])
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 220, in <listcomp>
    return b''.join([msg for msg in msgs])
  File "/usr/local/lib64/python3.8/site-packages/spu/binding/util/distributed.py", line 240, in <genexpr>
    rsp_data = rebuild_messages(rsp_itr.data for rsp_itr in rsp_gen)
  File "/usr/local/lib64/python3.8/site-packages/grpc/_channel.py", line 426, in __next__
    return self._next()
  File "/usr/local/lib64/python3.8/site-packages/grpc/_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused"
        debug_error_string = "UNKNOWN:Failed to pick subchannel {created_time:"2022-12-20T05:10:53.619911+00:00", children:[UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: Failed to connect to remote host: Connection refused {created_time:"2022-12-20T05:10:53.6199095+00:00", grpc_status:14}]}"
```
----
Another error occurs when I am trying to install spu from source, which need to run
`sh build_and_packaging.sh -i`
but I got: 
```
[root@6cd766c57e0c spu]# sh build_and_packaging.sh -i
Start build wheel package...
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
cannot clone: Operation not permitted
Error: cannot re-exec process
Build exited with non-zero.
```
And the script terminated. It says "cannot clone: Operation not permitted", but I ran this as root. 

Thanks, looking forward for reply.

**Comment by rivertalk** [comment]
Hi @DuanYuFi, thanks for the detailed description.

I tried to search the error log via google, and got this
https://github.com/containers/buildah/issues/3726

Are you using docker or podman as the container engine? If yes, there maybe some additional configuration to do.

Thanks.

**Comment by DuanYuFi** [comment]
> Hi @DuanYuFi
> 
> Please check instructions at the beginning of each example. Basically, you to have to setup the spu cluster before running the example.
> 
> In `build_and_packaging.sh`, we would build the spu python package in docker container. It seems your docker is not ready. Please double check. Thanks.

Oh yeah, I'm sorry I just missed the instructions and saw them as a part of lisences XD, thanks.

**Comment by DuanYuFi** [comment]
> Hi @DuanYuFi, thanks for the detailed description.
> 
> I tried to search the error log via google, and got this [containers/buildah#3726](https://github.com/containers/buildah/issues/3726)
> 
> Are you using docker or podman as the container engine? If yes, there maybe some additional configuration to do.
> 
> Thanks.

I uses docker desktop on windows hhh, thanks for the solution, I'll check it. Really thanks.

**Comment by 6fj** [comment]
If docker is not working and you could setup other enviroment including bazel, python env, etc. You could check `build_wheel_entrypoint.sh`

After that, you could just `pip install` with the wheel. 

Since you are using windows, I think you should fix docker first however.

**Comment by DuanYuFi** [comment]
> 

Ok, if still don't work, I will transfer to linux docker. Thanks for your help.

**Comment by DuanYuFi** [comment]
After running the instructions, I successfully ran this example. And I will deal another problem with the current solutions. If I have further question, I will reopen this issue. Thanks everyone!
