### ISSUE TITLE
[Bug]: 在已经搭建隐语平台的2个机器上调用spu的pir脚本报brpc错误

### ISSUE THREAD

**Issue by lukey** [secretflow/spu#531]
### Issue Type

Build/Install

### Modules Involved

PIR

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.8.0.dev20240112

### OS Platform and Distribution

Linux version 3.10.0-1160.80.1.el7.x86_64 

### Python Version

3.8

### Compiler Version

gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

### Current Behavior?

brpc server failed start

### Standalone code to reproduce the issue

```Python
python /home/app/spu/examples/python/pir/pir_server.py --party_ips 10.46.139.251:61307,10.46.139.4:61307 --rank 1 --oprf_key_path /home/app/spu/oprf_key.bin --setup_path setup_path --enable_tls False
```

### Relevant log output

```Shell
(sfhost) python /home/app/spu/examples/python/pir/pir_server.py --party_ips 10.46.139.251:9092,10.46.139.4:9092 --rank 1 --oprf_key_path /home/app/spu/oprf_key.bin --setup_path setup_path --enable_tls False
id_0 = 10.46.139.251:9092
id_1 = 10.46.139.4:9092
2024-02-01 17:16:57.806 [error] [server.cpp:BRPC:1054] Fail to listen 10.46.139.4:9092
2024-02-01 17:16:57.824 [warning] [channel.h:~Channel:160] Channel destructor is called before WaitLinkTaskFinish, try stop send thread
Traceback (most recent call last):
  File "/home/app/spu/examples/python/pir/pir_server.py", line 94, in <module>
    app.run(main)
  File "/home/app/anaconda3/envs/sfhost/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/app/anaconda3/envs/sfhost/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/app/spu/examples/python/pir/pir_server.py", line 87, in main
    link_ctx = setup_link(FLAGS.rank)
  File "/home/app/spu/examples/python/pir/pir_server.py", line 70, in setup_link
    return link.create_brpc(lctx_desc, rank)
RuntimeError: what:
        [external/yacl/yacl/link/transport/brpc_link.cc:101] brpc server failed start
stacktrace:
#0 yacl::link::FactoryBrpc::CreateContext()+0x2af49bcc5bf4
#1 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x2af49a7d8f84
#2 pybind11::cpp_function::dispatcher()+0x2af49a7af83e
#3 PyCFunction_Call+0x4f5572


(sfhost)
```

**Comment by Chrisdehe** [comment]
--partyips ip0:port0,ip1:port1 --rank 0/1
指定本方是rank 0 时，必须有ip0, 端口port0没有被占用
指定本方是rank 1 时，必须有ip1, 端口port1没有被占用

**Comment by lukey** [comment]
> --partyips ip0:port0,ip1:port1 --rank 0/1 指定本方是rank 0 时，必须有ip0, 端口port0没有被占用 指定本方是rank 1 时，必须有ip1, 端口port1没有被占用

确定没有被占用，还试过新的

**Comment by Chrisdehe** [comment]
报错看起来是连接不到10.46.139.4:9092的机器，核查一下是否按照以下方式配置了。
另外 你的sever端应该是rank0，client端应该是rank1
--partyips ip0:port0,ip1:port1 --rank 0/1
指定本方是rank 0 时，--partyips ip0:port0 --rank=0
指定本方是rank 1 时，--partyips ip1:port1 --rank=1

**Comment by lukey** [comment]
> 报错看起来是连接不到10.46.139.4:9092的机器，核查一下是否按照以下方式配置了。 另外 你的sever端应该是rank0，client端应该是rank1 --partyips ip0:port0,ip1:port1 --rank 0/1 指定本方是rank 0 时，--partyips ip0:port0 --rank=0 指定本方是rank 1 时，--partyips ip1:port1 --rank=1

成功，这个补充很关键
