### ISSUE TITLE
[Bug]:编译运行jnp_debug的问题

### ISSUE THREAD

**Issue by biexin666666** [secretflow/spu#541]
### Issue Type

Build/Install

### Modules Involved

Documentation/Tutorial/Example

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0988eec76721b5419693b979e5709b7b4c3becde

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.10

### Compiler Version

GCC 11.4.0

### Current Behavior?

老师您好，我是跟着隐语mooc《如何基于spu开发cheetah协议》 学习操作的。我在编译运行示例jnp_debug时，出现了如下问题，想请教一下如何解决。
```
(base) root@2dabb1e2a1eb:/home/admin/dev# bazel build -c opt spu/tests:jnp_debug
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:algebraic_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:batch_dot_simplification'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:batchnorm_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:bitcast_dtypes_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:call_inliner'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:cholesky_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:conditional_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:conditional_to_select'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:convolution_4d_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:convolution_group_converter'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:dot_decomposer'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:eigh_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:float_normalization'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:gather_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:gather_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_constant_folding'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_cse'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_dce'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_pass_pipeline'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:map_inliner'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:operand_upcaster'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:qr_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:real_imag_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:reshape_mover'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:result_caster'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:scatter_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:slice_sinker'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:sort_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:triangular_solve_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:while_loop_constant_sinking'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:while_loop_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:zero_sized_hlo_elimination'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service/gpu:dot_dimension_sorter'. Continuing because --nocheck_visibility is active
INFO: Analyzed target //spu/tests:jnp_debug (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //spu/tests:jnp_debug up-to-date:
  bazel-bin/spu/tests/jnp_debug
INFO: Elapsed time: 1.384s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
```
(base) root@2dabb1e2a1eb:/home/admin/dev# bazel-bin/spu/tests/jnp_debug
Traceback (most recent call last):
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/tests/jnp_debug.py", line 41, in <module>
    z = spu_fn(x, y)
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/simulation.py", line 154, in wrapper
    executable, output = spu_fe.compile(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 220, in compile
    ir_text, output = _jax_compilation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 123, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/tests/jnp_debug.py", line 38, in <lambda>
    fn = lambda x, y: si.example_binary(x, y)
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/intrinsic/example_binary_impl.py", line 17, in example_binary
    return _example_binary_prim.bind(in1, in2)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: custom_call() got an unexpected keyword argument 'out_types'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/tests/jnp_debug.py", line 41, in <module>
    z = spu_fn(x, y)
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/simulation.py", line 154, in wrapper
    executable, output = spu_fe.compile(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 220, in compile
    ir_text, output = _jax_compilation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 123, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/intrinsic/example_binary_impl.py", line 54, in _example_binary_lowering
    return custom_call(
TypeError: custom_call() got an unexpected keyword argument 'out_types'
```

### Standalone code to reproduce the issue

```Python
(base) root@2dabb1e2a1eb:/home/admin/dev# bazel build -c opt spu/tests:jnp_debug
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:algebraic_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:batch_dot_simplification'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:batchnorm_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:bitcast_dtypes_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:call_inliner'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:cholesky_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:conditional_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:conditional_to_select'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:convolution_4d_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:convolution_group_converter'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:dot_decomposer'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:eigh_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:float_normalization'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:gather_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:gather_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_constant_folding'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_cse'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_dce'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:hlo_pass_pipeline'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:map_inliner'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:operand_upcaster'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:qr_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:real_imag_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:reshape_mover'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:result_caster'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:scatter_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:slice_sinker'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:sort_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:triangular_solve_expander'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:while_loop_constant_sinking'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:while_loop_simplifier'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service:zero_sized_hlo_elimination'. Continuing because --nocheck_visibility is active
WARNING: /home/admin/dev/libspu/compiler/front_end/BUILD.bazel:17:15: in cc_library rule //libspu/compiler/front_end:hlo_importer: Target '//libspu/compiler/front_end:hlo_importer' violates visibility of target '@xla//xla/service/gpu:dot_dimension_sorter'. Continuing because --nocheck_visibility is active
INFO: Analyzed target //spu/tests:jnp_debug (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //spu/tests:jnp_debug up-to-date:
  bazel-bin/spu/tests/jnp_debug
INFO: Elapsed time: 1.384s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
(base) root@2dabb1e2a1eb:/home/admin/dev# bazel-bin/spu/tests/jnp_debug
Traceback (most recent call last):
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/tests/jnp_debug.py", line 41, in <module>
    z = spu_fn(x, y)
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/simulation.py", line 154, in wrapper
    executable, output = spu_fe.compile(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 220, in compile
    ir_text, output = _jax_compilation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 123, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/tests/jnp_debug.py", line 38, in <lambda>
    fn = lambda x, y: si.example_binary(x, y)
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/intrinsic/example_binary_impl.py", line 17, in example_binary
    return _example_binary_prim.bind(in1, in2)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: custom_call() got an unexpected keyword argument 'out_types'

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/tests/jnp_debug.py", line 41, in <module>
    z = spu_fn(x, y)
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/simulation.py", line 154, in wrapper
    executable, output = spu_fe.compile(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 220, in compile
    ir_text, output = _jax_compilation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/utils/frontend.py", line 123, in _jax_compilation
    cfn, output = jax.xla_computation(
  File "/home/admin/dev/bazel-bin/spu/tests/jnp_debug.runfiles/spulib/spu/intrinsic/example_binary_impl.py", line 54, in _example_binary_lowering
    return custom_call(
TypeError: custom_call() got an unexpected keyword argument 'out_types'
```

**Comment by anakinxc** [comment]
Hi @biexin666666 

这里的`si.example_binary` 和新的 jax 兼容性有点问题，我晚点 fix 一下

你可以先暂时换成别的比如 x*y 这种
