### ISSUE TITLE
mac运行spu-psi_test中.so错误

### ISSUE THREAD

**Issue by Yinbenxin** [secretflow/spu#637]
### Issue Type

Build/Install

### Modules Involved

SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

0.9.0

### OS Platform and Distribution

mac M1 13.31

### Python Version

3.11

### Compiler Version

14.0.3

### Current Behavior?

pip install spu
python setup.py bdist_wheel
pip install dist/*.whl --force-reinstall
完成以上命令成功编译出.so，我们电脑是arm64，但need 'x86_64'
执行测试 bazel run -c opt //spu/tests:psi_test  出现问题

### Standalone code to reproduce the issue

```Python
(spu) (base) admin@YZSJ-GDDN-0012 spu % bazel run -c opt //spu/tests:psi_test
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Analyzed target //spu/tests:psi_test (4 packages loaded, 214 targets configured).
INFO: Found 1 target...
Target //spu/tests:psi_test up-to-date:
  bazel-bin/spu/tests/psi_test
INFO: Elapsed time: 2.257s, Critical Path: 0.06s
INFO: 6 processes: 4 internal, 2 darwin-sandbox.
INFO: Build completed successfully, 6 total actions
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh spu/tests/psi_test
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //spu/tests:psi_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/tests/psi_test.py", line 22, in <module>
    import spu.libspu.link as link
ImportError: dlopen(/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so, 0x0002): tried: '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so' (no such file), '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/libspu.so' (no such file), '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

### Relevant log output

```Shell
(spu) (base) admin@YZSJ-GDDN-0012 spu % bazel run -c opt //spu/tests:psi_test
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Analyzed target //spu/tests:psi_test (4 packages loaded, 214 targets configured).
INFO: Found 1 target...
Target //spu/tests:psi_test up-to-date:
  bazel-bin/spu/tests/psi_test
INFO: Elapsed time: 2.257s, Critical Path: 0.06s
INFO: 6 processes: 4 internal, 2 darwin-sandbox.
INFO: Build completed successfully, 6 total actions
INFO: Running command line: external/bazel_tools/tools/test/test-setup.sh spu/tests/psi_test
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //spu/tests:psi_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/tests/psi_test.py", line 22, in <module>
    import spu.libspu.link as link
ImportError: dlopen(/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so, 0x0002): tried: '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so' (no such file), '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/tests/psi_test.runfiles/spulib/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/libspu.so' (no such file), '/private/var/tmp/_bazel_admin/13fc870f323ba41e43f95aeadce89fe0/execroot/spulib/bazel-out/darwin_arm64-opt/bin/spu/libspu.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by anakinxc** [comment]
请确定你的 python 是 arm64 的

**Comment by Yinbenxin** [comment]
重装bazel之后问题解决了，重装的版本是6.5.0

**Comment by Chrisdehe** [comment]
@Yinbenxin 请问你之前bazel的版本是多少呢？

**Comment by Yinbenxin** [comment]
7.1.1

**Comment by Chrisdehe** [comment]
@Yinbenxin 
hey，经过复现并没有显示出同样的问题，为了解决此问题二次发生，你是否愿意pr下能够复现的过程呢？或者可以添加隐语技术支持来快速沟通（secretflow02）

**Comment by Yinbenxin** [comment]
不过也可能是python版本的问题，我当时重装了python和bazel，已经将问题解决，但是之前的原因出现在哪并不清楚，复现难度较大。

**Comment by Chrisdehe** [comment]
好的

**Comment by Yinbenxin** [comment]
找到问题所在了，是我本机安装的python版本不对，在测试pybind11时，对编译后的内容进行调用时出现类似的错误：
>>> import add
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/admin/Desktop/code/pybind11-master/Day 1 add/cmake-build-debug/add.cpython-39-darwin.so, 0x0002): tried: '/Users/admin/Desktop/code/pybind11-master/Day 1 add/cmake-build-debug/add.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/admin/Desktop/code/pybind11-master/Day 1 add/cmake-build-debug/add.cpython-39-darwin.so' (no such file), '/Users/admin/Desktop/code/pybind11-master/Day 1 add/cmake-build-debug/add.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by Chrisdehe** [comment]
确认一下 是python==11的时候发生的问题吗？

**Comment by Chrisdehe** [comment]
感谢对隐语社区的反馈！！！
祝好！

**Comment by Chrisdehe** [comment]
@Yinbenxin 嗨～ 非常感谢你在#107issue的贡献，我们欢迎你加入到隐语开源社区，与来自不同地区行业的优秀人士共建、共创，一起为打造数据要素时代的基础设施贡献力量，期待你的到来。（secretflow02）
