### ISSUE TITLE
[Bug]: Error when trying to benchmark SPU latency in 2PC setting.

### ISSUE THREAD

**Issue by wilyub** [secretflow/spu#663]
### Issue Type

Usability

### Modules Involved

MPC protocol, SPU runtime

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

spu 0.9.0b1

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python Version

3.11.5

### Current Behavior?

I'm trying to benchmark the latency of performing one matrix multiplication using the SPU. I'm working with a 2PC setting so I open two servers and run the following commands (one on each node): I've included the full code in the code section.
- python nodectl.py -c 2pc.json start --node_id node:0 &> node0.log &
- python nodectl.py -c 2pc.json start --node_id node:1 &> node1.log &
Afterwards, I run my multiplication test script on node 0 (script found below). I get an error (shown in the log section). Any idea what I can fix? Also one additional note, both of my nodes are running Singularity Containers. Not sure if that plays any part in this.

### Standalone code to reproduce the issue

```Python
#nodectl.py file

import argparse
import json
import multiprocess
import sys

import grpc
import jax

import spu.utils.distributed as ppd
from spu.utils import distributed_pb2_grpc

parser = argparse.ArgumentParser(description='SPU node service.')
parser.add_argument(
    "-c", "--config", default="examples/python/conf/3pc.json", help="the config"
)
subparsers = parser.add_subparsers(dest='command')
parser_start = subparsers.add_parser('start', help='to start a single node')
parser_start.add_argument("-n", "--node_id", default="node:0", help="the node id")
parser_up = subparsers.add_parser('up', help='to bring up all nodes')
parser_list = subparsers.add_parser('list', help='list node information')
parser_list.add_argument("-v", "--verbose", action='store_true', help="verbosely")

if __name__ == '__main__':
    args = parser.parse_args()

    with open(args.config, 'r') as file:
        conf = json.load(file)

    nodes_def = conf["nodes"]
    devices_def = conf["devices"]

    if args.command == 'start':
        ppd.RPC.serve(args.node_id, nodes_def)
    elif args.command == 'up':
        workers = []
        for node_id in nodes_def.keys():
            worker = multiprocess.Process(
                target=ppd.RPC.serve, args=(node_id, nodes_def)
            )
            worker.start()
            workers.append(worker)

        for worker in workers:
            worker.join()
    else:
        parser.print_help()


#2pc.json file
{
    "id": "colocated.2pc",
    "nodes": {
        "node:0": "10.32.35.27:9320",
        "node:1": "10.32.35.42:9321"
    },
    "devices": {
        "SPU": {
            "kind": "SPU",
            "config": {
                "node_ids": [
                    "node:0",
                    "node:1"
                ],
                "experimental_data_folder": [
                    "/tmp/spu_data_0/",
                    "/tmp/spu_data_1/"
                ],
                "spu_internal_addrs": [
                    "10.32.35.27:9330",
                    "10.32.35.42:9331"
                ],
                "runtime_config": {
                    "protocol": "SEMI2K",
                    "field": "FM128",
                    "enable_pphlo_profile": true,
                    "enable_hal_profile": true,
                    "enable_pphlo_trace": false,
                    "enable_action_trace": false
                }
            }
        },
        "P1": {
            "kind": "PYU",
            "config": {
                "node_id": "node:0"
            }
        },
        "P2": {
            "kind": "PYU",
            "config": {
                "node_id": "node:1"
            }
        }
    }
}

#Multiplication Test Code
import sys
import os
sys.path.append(os.path.abspath('..'))
import argparse
import json
import jax
import jax.numpy as jnp
import jax.nn as jnn
import numpy as np
import flax
import spu.utils.distributed as ppd
import spu.spu_pb2 as spu_pb2

parser = argparse.ArgumentParser(description='distributed driver.')
parser.add_argument(
    "-c", "--config", default="2pc.json"
)
parser.add_argument('--workers', default=1, type=int, metavar='N', help='number of data loading workers (default: 4)')
parser.add_argument('--batch', default=1, type=int, metavar='N', help='batchsize (default: 64)')
args = parser.parse_args()
with open(args.config, 'r') as file:
    conf = json.load(file)
ppd.init(conf["nodes"], conf["devices"])

def test_matmul(x, y):
    result = jnp.matmul(x,y)
    return result

def run_on_spu(input1, input2):
    input_p1 = ppd.device("P1")(lambda x: x)(input1)
    input_p2 = ppd.device("P2")(lambda x: x)(input2)
    outputs = ppd.device("SPU")(test_matmul)(input_p1, input_p2)
    outputs = ppd.get(outputs)
    return outputs

if __name__ == '__main__':
    torch.manual_seed(0)
    print('\n------\nRun on SPU')
    out_spu = run_on_spu(np.random.rand(1,1), np.random.rand(1,1))
```

### Relevant log output

```Shell
[2024-04-23 10:55:03,934] [MainProcess] Starting grpc server at 10.32.35.27:9320
[2024-04-23 10:55:14,235] [MainProcess] Run : builtin_spu_init at node:0
I0423 10:55:14.238981 1591474 external/com_github_brpc_brpc/src/brpc/server.cpp:1181] Server[yacl::link::transport::internal::ReceiverServiceImpl] is serving on port=9330.
W0423 10:55:14.239002 1591474 external/com_github_brpc_brpc/src/brpc/server.cpp:1187] Builtin services are disabled according to ServerOptions.has_builtin_services
I0423 10:55:14.340871 1591476 external/com_github_brpc_brpc/src/brpc/socket.cpp:2506] Checking Socket{id=0 addr=10.32.35.42:9331} (0x154c8804b8c0)
I0423 10:56:53.474580 1591474 external/com_github_brpc_brpc/src/brpc/server.cpp:1241] Server[yacl::link::transport::internal::ReceiverServiceImpl] is going to quit
[2024-04-23 10:56:53.475] [warning] [channel.h:163] Channel destructor is called before WaitLinkTaskFinish, try stop send thread
[2024-04-23 10:56:53,476] [MainProcess] Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.11/site-packages/spu/utils/distributed_impl.py", line 326, in Run
    ret_objs = fn(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ext3/miniconda3/lib/python3.11/site-packages/spu/utils/distributed_impl.py", line 552, in builtin_spu_init
    link = libspu.link.create_brpc(desc, my_rank)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: what: 
	[external/yacl/yacl/link/context.cc:194] connect to mesh failed, failed to setup connection to rank=1
stacktrace: 
#0 pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()+0x154ce94615c4
#1 pybind11::cpp_function::dispatcher()+0x154ce94353eb
#2 cfunction_call+0x525f07
```

**Comment by Chrisdehe** [comment]
@wilyub hey,Please note that rank=1 is mostly due to connection issues with the participating parties. Please check and ensure that your 2PC is connected.

**Comment by tpppppub** [comment]
It seems to be a network problem. Please make sure the two nodes/ports are accessible by each other. Besides, using port range 60000-65535 is recommended to eliminate the possible conflicts with other processes/services.
