### ISSUE TITLE
[Bug]: 编译出错

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/spu#843]
### Issue Type

Build/Install

### Modules Involved

Others

### Have you reproduced the bug with SPU HEAD?

Yes

### Have you searched existing issues?

Yes

### SPU Version

最新

### OS Platform and Distribution

Ubuntu 22.04

### Python Version

3.10

### Current Behavior?

您好，我在安装好依赖后执行了下列命令
```
python3 -m pip install -r requirements.txt
python3 -m pip install -r requirements-dev.txt
python setup.py bdist_wheel
pip install dist/*.whl --force-reinstall
```
安装之后我尝试用导入spu会报错，而且运行pip install dist/*.whl --force-reinstall也会提示依赖版本冲突，请问如何解决？

### Standalone code to reproduce the issue

```Python
尝试导入spu的报错：
Traceback (most recent call last):
  File "/home/admin/dev/spu/test.py", line 1, in <module>
    import spu
  File "/home/admin/dev/spu/spu/__init__.py", line 16, in <module>
    from . import experimental, psi
  File "/home/admin/dev/spu/spu/psi.py", line 19, in <module>
    from . import libpsi  # type: ignore
ImportError: cannot import name 'libpsi' from partially initialized module 'spu' (most likely due to a circular import) (/home/admin/dev/spu/spu/__init__.py)

依赖冲突：
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flax 0.9.0 requires jax>=0.4.27, but you have jax 0.4.26 which is incompatible.
optax 0.2.3 requires jax>=0.4.27, but you have jax 0.4.26 which is incompatible.
optax 0.2.3 requires jaxlib>=0.4.27, but you have jaxlib 0.4.26 which is incompatible.
tensorflow-cpu 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.1.0 which is incompatible.
```

**Comment by anakinxc** [comment]
不要在 spu 目录下 import spu

**Comment by zzx-QDU** [comment]
您好，我还想问下那些依赖冲突会有影响吗？

**Comment by anakinxc** [comment]
> 您好，我还想问下那些依赖冲突会有影响吗？

大部分情况下应该没有，如果有问题可以装 `jax>=0.4.27`

**Comment by zzx-QDU** [comment]
好的 非常感谢
